# Generated by Django 6.0.5 on 2026-07-17 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0005_remove_item_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_terms_days', models.IntegerField(default=30, help_text='e.g., Net 30')),
                ('internal_rating', models.CharField(choices=[('A', 'Excellent (Prompt Payer)'), ('B', 'Good (Standard Terms)'), ('C', 'Risky (Late Payer)')], default='B', max_length=1)),
                ('lifetime_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('negotiation_notes', models.TextField(blank=True, help_text='Private notes for the sales manager')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_profile', to='tracker.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('VOID', 'Voided')], default='DRAFT', max_length=20)),
                ('ocr_document', models.FileField(blank=True, null=True, upload_to='invoices_pdfs/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tracker.customer')),
                ('offer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='tracker.offer')),
            ],
        ),
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('COST', 'Purchase Cost (From Supplier)'), ('SALE', 'Sale Price (To Client)')], max_length=4)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('supplier_or_client_name', models.CharField(max_length=255)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.invoice')),
            ],
        ),
    ]
