# Generated by Django 6.0.5 on 2026-07-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_qrs/'),
        ),
    ]
