# Generated by Django 6.0.5 on 2026-07-21 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_invoice_qr_code'),
        ('tracker', '0006_item_current_piraeus_bin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='pricerecord',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='google_drive_url',
            field=models.URLField(blank=True, help_text='Paste Google Drive shareable link for this invoice', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clientfinancialprofile',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to='tracker.customer'),
        ),
        migrations.AlterField(
            model_name='clientfinancialprofile',
            name='internal_rating',
            field=models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Good'), ('C', 'C - Risky')], default='B', max_length=5),
        ),
        migrations.AlterField(
            model_name='clientfinancialprofile',
            name='negotiation_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientfinancialprofile',
            name='payment_terms_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tracker.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ocr_document',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PAID', 'Paid'), ('VOID', 'Void')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricerecord',
            name='currency',
            field=models.CharField(default='EUR', max_length=10),
        ),
        migrations.AlterField(
            model_name='pricerecord',
            name='part_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pricerecord',
            name='supplier_or_client_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pricerecord',
            name='transaction_type',
            field=models.CharField(default='Purchase', max_length=50),
        ),
    ]
