# Generated by Django 6.0.5 on 2026-07-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_invoice_offer_remove_invoice_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='ocr_document',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='google_drive_url',
            field=models.URLField(blank=True, help_text='Google Drive shareable link for this invoice', max_length=500, null=True),
        ),
    ]
