# Generated by Django 6.0.5 on 2026-07-22 13:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_invoice_ocr_document_and_more'),
        ('tracker', '0006_item_current_piraeus_bin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricerecord',
            options={'ordering': ['-date_recorded']},
        ),
        migrations.RemoveField(
            model_name='pricerecord',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='pricerecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.customer'),
        ),
        migrations.AddField(
            model_name='pricerecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricerecord',
            name='part_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientfinancialprofile',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.customer'),
        ),
        migrations.AlterField(
            model_name='clientfinancialprofile',
            name='internal_rating',
            field=models.CharField(default='B', max_length=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='google_drive_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT / INVOICE'), ('ORDER', 'ORDER (Παραγγελία)'), ('DELIVERY', 'DELIVERY NOTE (Δελτίο Αποστολής)'), ('PAID', 'PAID'), ('VOID', 'VOID')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricerecord',
            name='date_recorded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pricerecord',
            name='part_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pricerecord',
            name='supplier_or_client_name',
            field=models.CharField(max_length=255),
        ),
    ]
