# Generated by Django 6.0.5 on 2026-07-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_pricerecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPricelistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
                ('part_code', models.CharField(blank=True, help_text='OEM or Manufacturer Part Number', max_length=100, null=True)),
                ('category', models.CharField(choices=[('Filters', 'Filters & Separators'), ('Electrical', 'Electrical & Batteries'), ('Pumps', 'Pumps & Impellers'), ('Valves', 'Valves & Plumbing'), ('Engine Spares', 'Engine Spares'), ('General', 'General Marine Hardware')], default='General', max_length=50)),
                ('brand', models.CharField(blank=True, help_text='e.g. Yanmar, Victron, Jabsco', max_length=100, null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Internal Purchase Cost (€)', max_digits=10)),
                ('markup_percent', models.DecimalField(decimal_places=2, default=30.0, help_text='Default Markup %', max_digits=5)),
                ('client_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated Selling Price (€)', max_digits=10)),
                ('availability', models.CharField(choices=[('In Stock', 'In Stock (Piraeus Warehouse)'), ('2-3 Days', 'Available (2-3 Business Days)'), ('7-10 Days', 'Special Order (7-10 Days)')], default='In Stock', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'part_name'],
            },
        ),
    ]
