# Generated by Django 6.0.5 on 2026-05-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_compartment_location_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
