# Generated by Django 6.0.5 on 2026-05-28 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_item_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='tracker.offer'),
        ),
    ]
