# Generated by Django 6.0.5 on 2026-07-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_item_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='qr_code',
        ),
    ]
