# Generated by Django 6.0.5 on 2026-07-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_item_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_piraeus_bin',
            field=models.CharField(blank=True, help_text='Current bin location (e.g., Rack A2)', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='destination_facility_bin',
            field=models.CharField(blank=True, help_text='Target location for the reorganization', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='transfer_status',
            field=models.CharField(choices=[('ACTIVE', 'Active Stock'), ('UNUTILIZED', 'Unutilized / Purge'), ('PACKED', 'Ready for Transfer'), ('MOVED', 'Transferred to New Facility')], default='ACTIVE', max_length=20),
        ),
    ]
