# Generated by Django 6.0.5 on 2026-07-23 11:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_item_current_piraeus_bin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='compartment',
        ),
        migrations.RemoveField(
            model_name='item',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='customer',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
                ('part_code', models.CharField(blank=True, help_text='OEM / Part Number', max_length=100, null=True)),
                ('category', models.CharField(choices=[('Filters', 'Filters & Separators'), ('Electrical', 'Electrical & Batteries'), ('Pumps', 'Pumps & Impellers'), ('Valves', 'Valves & Plumbing'), ('Engine Spares', 'Engine Spares'), ('General', 'General Hardware')], default='General', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=5, help_text='Alert trigger when stock drops below this level')),
                ('location', models.CharField(default='Piraeus Warehouse', help_text='Shelf / Bin / Rack', max_length=100)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.customer')),
            ],
            options={
                'ordering': ['category', 'part_name'],
            },
        ),
        migrations.DeleteModel(
            name='Compartment',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
