# Generated by Django 6.0.5 on 2026-07-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_packed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Electrical', 'Electrical'), ('Filters', 'Filters'), ('Pumps', 'Pumps'), ('Valves', 'Valves')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(default='Piraeus Warehouse', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='part_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.IntegerField(default=5),
        ),
    ]
